name: Calculate Compatibility Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'functions/calculateCompatibility/**'

jobs:
  build:
    uses: ./.github/workflows/build-test.yml
    with:
      function_name: calculateCompatibility
    secrets: inherit

  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/deploy-targeted.yml
  #   with:
  #     module_name: calculate_compatibility
  #   secrets: inherit