name: Delete Compatibility Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'functions/deleteCompatibility/**'

jobs:
  build:
    uses: ./.github/workflows/build-test.yml
    with:
      function_name: deleteCompatibility
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-targeted.yml
    with:
      module_name: delete_compatibility
    secrets: inherit