name: Shared Module Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: Terraform-Apply
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd terraform/environments/prod
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/environments/prod
          terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        run: |
          cd terraform/environments/prod
          terraform apply tfplan