# name: Shared Module Deploy

# on:
#   push:
#     paths:
#       - 'terraform/**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     concurrency:
#       group: Terraform-Apply
#       cancel-in-progress: true
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#       - name: Terraform Init
#         run: |
#           cd terraform/environments/prod
#           terraform init
#       - name: Terraform Plan
#         run: |
#           cd terraform/environments/prod
#           terraform plan -var-file=terraform.tfvars -out=tfplan
#       - name: Terraform Apply
#         run: |
#           cd terraform/environments/prod
#           terraform apply tfplan